### ISSUE TITLE
AtCoder Rating Cumulative Distribution のバグ報告

### ISSUE THREAD

**Issue by harurunrunrun** [AAAR-Salmon/Userscripts#2]
# 累積# 累積% のいずれかを押した状態で、# 累積# 累積% のいずれかを押すとグラフが1回り小さくなります。
(押した分だけ小さくなります。)

**Comment by AAAR-Salmon** [comment]
報告ありがとうございます。
RetinaディスプレイやWindowsの拡大鏡などを使用して、`devicePixelRatio != 1` であるときに発生する不具合だったようです。
確認し、修正しました。
